language: node_js
node_js:
- 5.3.0
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- $CI_ACTION
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - TEST_SUITE=unit
  - GH_REF: github.com/gasolin/webby.git
  - secure: QCKLoRO4V/amAXaxSoLPWq4FXPJioSzlEBuZOu7qCXkfbXC5KjSgUnAzgi2hpiRo7nqZ6EiraHljSr8X0U4XXShBMeDUofFOxuO4IJE8FvdJKLxC1E0/A+mR6oqz30jXG6rpzHv6lHhrMf6gbfkKPQC2LH4/Kug9Y0e+guLOnfVV0+H4gzPKhCwAN02wFGEp4BOGP9bPPRIz5KCUxV2z/dXC667bUl0BYqbAvWod2hKWg9BVUUJVjQUCfWGEWbGWx7upVOZFMq2TSF4Chjhr1eVodqGF3P5PDaEAfERB9DciQOG7NMmhlDv8YdRi/J3/KHDBZ5kqM0ALVN6dgBGddUSoeE3KzG9m+v+33e6ZmS0YqUjf7K84z4inf7b6lTXRPiGpYARGvQEAxYSVka06ml0VIwFWDMewx2ygyyp9HOdCyoSgEEPRRcYkmm++TAy7fyAXtLd/vBZwzmnjfYbnG6/a5ejf/TMxhT0NwYED28IcRkYIPLV/uq/5VZ9BNEy3+9wWZ9ClywBrx/xL8GC9bM7lNH+/4Fyj65NBWk8MIQ+SR4UJOdXR/PGDV8lFkqNJiERhrJwm5Dm6bqbo9ec09uJ4/kUF1hdicVh7naUQUwo+S8dxFgPMvSpPGNrtXyFYaVazr/FIDgflTILjznveMBQRoqhvBIa6ulNxMX2cBBM=
  - secure: ik2wvhYurNYimv3OAiZ/fFMwo3Qn4ShZgWk67P1jGZQUp7JMwZ8fm/gIKyJlLokjOg1Me4sXohI+iC338v3r/vnvgumf6baLYlhu0c9W6GlCiJqLfnuhA3JODu4dTvI5Sd5h5qTTWDMBgUwXJuu8mZ0QRpdH/pwzvhoAwX3mKVSxDRT7efLG2ayJD2TFSmRW+I+o/s3vMYRXJK1WpuNWcm0ECkXUbpnewCZpUtizRBo17ODo2q33iyeprayLMKc2rzoUe7Te+OWoJDTriw+X7DqP3P8InvgJAkj1NcUAIhb7zleCwJTEiqwfGf8D2eWiVRmDF6X3OlKoCK92RZiqJJTBTZZr4DnPL/DfNCtGWvtqlEWgsfEBZSlANTm7c1u6PZDGeI6VnjA3ImDXeHJx32RA/8XNQFBaITlKIoB18OvRP5i5vpAiMNT2tWGyymEcWX4+2GnLLZT+mDACsAe58DmFn9XRotSEYCJ+G6jMVybIQhwMxSg+dBkOlEk3cei38UyqrD2twB/QSahJkyesYZsVFfM9A5JoR0c21S+Rv7mS3hYuoCWsoJcWex969LfDqJKnsKXcQR88R6wr603q7Z3NfnZMVBzkHGLuqVy5LYvISmtYAZxbzWxzZiHatFVZwV7j7ntt3TBElwECpLkxyJGkm2I07TyTtfL3003LAiQ=
  matrix:
  - CI_ACTION="npm run lint"
  - CI_ACTION="npm test"
